### ISSUE TITLE
Race in `Fiber.Id`

### ISSUE THREAD

**Issue by gadmm** [dbuenzli/affect#2]
https://github.com/dbuenzli/affect/blob/21219985d9c96a08d8bc1d1049a78f8ee3579c8b/src/fiber.ml#L20

It looks like this is susceptible to the races: `incr1 -> incr2 -> get1 -> get2` or `incr1 -> incr2 -> get2 -> get1`. Do you mean `1 + (Atomic.fetch_and_add id 1)` ?

**Comment by dbuenzli** [comment]
Indeed I still have a single threaded trained brain…

Thanks for looking @gadmm !

**Comment by gadmm** [comment]
Between us, `Atomic.incr` would be more useful if it returned the value (but this ship has sailed).
